In [14]:
import pandas as pd
import numpy as np

df = pd.read_csv("titanic.csv", delimiter = ",")

In [15]:
print(df[["Age", "Sex"]].head(5))

    Age     Sex
0  22.0    male
1  38.0  female
2  26.0  female
3  35.0  female
4  35.0    male

In [16]:
df["Realtives"] = df["SibSp"] + df["Parch"] 
print(len(df[~df["Realtives"].isin([0])]))
print(len(df[df["Embarked"].isin(["S"])]))

354
644

In [17]:
surv = len(df[df["Survived"].isin([1])])
not_surv = len(df[df["Survived"].isin([0])])
print(f"Survived: {surv}")
print(f"Not survived: {not_surv}")

Survived: 342
Not survived: 549

In [18]:
dct = {1 : "Elitarii", 2 : "Srednenkiy", 3 : "Nishuk"}

df = df.replace({"Pclass" : dct})

df["Fare_bin"] = "Dorogo bogato"
df.loc[(df.Fare < 20), "Fare_bin"] = "Mog by i potratica"

df = df.dropna()
df = df.reset_index()
df

,index,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Realtives,Fare_bin
0,1,2,1,Elitarii,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,1,Dorogo bogato
1,3,4,1,Elitarii,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,1,Dorogo bogato
2,6,7,0,Elitarii,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S,0,Dorogo bogato
3,10,11,1,Nishuk,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S,2,Mog by i potratica
4,11,12,1,Elitarii,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S,0,Dorogo bogato
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
178,871,872,1,Elitarii,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S,2,Dorogo bogato
179,872,873,0,Elitarii,"Carlsson, Mr. Frans Olof",male,33.0,0,0,695,5.0000,B51 B53 B55,S,0,Mog by i potratica
180,879,880,1,Elitarii,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C,1,Dorogo bogato
181,887,888,1,Elitarii,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,0,Dorogo bogato
182,889,890,1,Elitarii,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,0,Dorogo bogato